In [3]:
import numpy as np
#Creating an array of 3x1 column vector
x=np.array([[1],[2],[3]])
print(x)

[[1]
 [2]
 [3]]


In [7]:
#using transspose for aboove column vector to row vector
x=np.transpose(np.array([[1,2,3]]))
print(x)

[[1]
 [2]
 [3]]


In [8]:
#using T for transpose
x=np.array([[1,2,3]]).T
print(x)


[[1]
 [2]
 [3]]


In [9]:
# ndarray.shape : gives Tuple of array dimensions
x.shape

(3, 1)

In [10]:
# np.dot for dot product
x=np.dot(3,4)
x

12

In [14]:
x=np.dot([3j,4j],[4j,4j])
x

(-28+0j)

In [16]:
x=np.dot([1,2],[3,4])
x

11

In [20]:
a=np.array([[1,1],[2,2]])
b=np.array([[3,4],[5,6]])
x=np.dot(a,b)
x

array([[ 8, 10],
       [16, 20]])

In [21]:
#np.sign Returns an element-wise indication of the sign of a number.

x=np.sign(0)
x

0

In [23]:
x=np.sign([-4.,5.])
x

array([-1.,  1.])

In [24]:
# np.sum :Sum of array elements over a given axis.

x=np.sum([1,2,3,4])
x

10

In [28]:
x=np.sum([1.0,2.3,3.8,5.6],dtype=np.int32)
x

11

In [34]:
x=np.sum([[1.0,2.3],[3.8,5.6]],axis=0)
x
x=np.sum([[1.0,2.3],[3.8,5.6]],axis=1)
x

array([3.3, 9.4])

In [39]:
# np.ones and np.zeros
x=np.zeros((2,3))
x

array([[0., 0., 0.],
       [0., 0., 0.]])

In [42]:
x=np.ones((1,2))
x

array([[1., 1.]])

In [45]:
#np.random.rand
x=np.random.rand(2,3)
x

array([[0.34891083, 0.69901898, 0.98516519],
       [0.73601541, 0.82906196, 0.72748469]])

In [3]:
import numpy as np
x=np.dot(np.transpose([[1],[2],[3],[4]]),[[1],[2],[3],[4]])
x

array([[30]])